package org.infinite.db.dao;

// Generated 20-apr-2009 10.52.17 by Hibernate Tools 3.2.4.CR1

/**
 * AreaItem generated by hbm2java
 */
public class AreaItem implements java.io.Serializable {

	private Integer id;
	private Area area;
	private Locks locks;
	private String name;
	private String icon;
	private short ax;
	private short ay;
	private Integer x;
	private Integer y;
	private String url;
	private boolean direct;

	public AreaItem() {
	}

	public AreaItem(Area area, Locks locks, String name, String icon, short ax,
			short ay, Integer x, Integer y, String url, boolean direct) {
		this.area = area;
		this.locks = locks;
		this.name = name;
		this.icon = icon;
		this.ax = ax;
		this.ay = ay;
		this.x = x;
		this.y = y;
		this.url = url;
		this.direct = direct;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Locks getLocks() {
		return this.locks;
	}

	public void setLocks(Locks locks) {
		this.locks = locks;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public short getAx() {
		return this.ax;
	}

	public void setAx(short ax) {
		this.ax = ax;
	}

	public short getAy() {
		return this.ay;
	}

	public void setAy(short ay) {
		this.ay = ay;
	}

	public Integer getX() {
		return this.x;
	}

	public void setX(Integer x) {
		this.x = x;
	}

	public Integer getY() {
		return this.y;
	}

	public void setY(Integer y) {
		this.y = y;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public boolean isDirect() {
		return this.direct;
	}

	public void setDirect(boolean direct) {
		this.direct = direct;
	}

}
