package org.infinite.db.dao;

// Generated 20-mag-2009 21.48.17 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AreaItem generated by hbm2java
 */
public class AreaItem implements java.io.Serializable {

	private Integer id;
	private String name;
	private String icon;
	private Integer cost;
	private Integer areaid;
	private short areax;
	private short areay;
	private Integer x;
	private Integer y;
	private String arealock;
	private String questlock;
	private String url;
	private boolean direct;
	private boolean loop;
	private boolean hidemode;
	private Integer areaItemLevel;
	private String npcs;
	private Set<Player> players = new HashSet<Player>(0);

	public AreaItem() {
	}

	public AreaItem(String name, String icon, Integer cost, Integer areaid,
			short areax, short areay, Integer x, Integer y, String arealock,
			String questlock, String url, boolean direct, boolean loop,
			boolean hidemode, Integer areaItemLevel, String npcs) {
		this.name = name;
		this.icon = icon;
		this.cost = cost;
		this.areaid = areaid;
		this.areax = areax;
		this.areay = areay;
		this.x = x;
		this.y = y;
		this.arealock = arealock;
		this.questlock = questlock;
		this.url = url;
		this.direct = direct;
		this.loop = loop;
		this.hidemode = hidemode;
		this.areaItemLevel = areaItemLevel;
		this.npcs = npcs;
	}

	public AreaItem(String name, String icon, Integer cost, Integer areaid,
			short areax, short areay, Integer x, Integer y, String arealock,
			String questlock, String url, boolean direct, boolean loop,
			boolean hidemode, Integer areaItemLevel, String npcs,
			Set<Player> players) {
		this.name = name;
		this.icon = icon;
		this.cost = cost;
		this.areaid = areaid;
		this.areax = areax;
		this.areay = areay;
		this.x = x;
		this.y = y;
		this.arealock = arealock;
		this.questlock = questlock;
		this.url = url;
		this.direct = direct;
		this.loop = loop;
		this.hidemode = hidemode;
		this.areaItemLevel = areaItemLevel;
		this.npcs = npcs;
		this.players = players;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	public Integer getAreaid() {
		return this.areaid;
	}

	public void setAreaid(Integer areaid) {
		this.areaid = areaid;
	}

	public short getAreax() {
		return this.areax;
	}

	public void setAreax(short areax) {
		this.areax = areax;
	}

	public short getAreay() {
		return this.areay;
	}

	public void setAreay(short areay) {
		this.areay = areay;
	}

	public Integer getX() {
		return this.x;
	}

	public void setX(Integer x) {
		this.x = x;
	}

	public Integer getY() {
		return this.y;
	}

	public void setY(Integer y) {
		this.y = y;
	}

	public String getArealock() {
		return this.arealock;
	}

	public void setArealock(String arealock) {
		this.arealock = arealock;
	}

	public String getQuestlock() {
		return this.questlock;
	}

	public void setQuestlock(String questlock) {
		this.questlock = questlock;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public boolean isDirect() {
		return this.direct;
	}

	public void setDirect(boolean direct) {
		this.direct = direct;
	}

	public boolean isLoop() {
		return this.loop;
	}

	public void setLoop(boolean loop) {
		this.loop = loop;
	}

	public boolean isHidemode() {
		return this.hidemode;
	}

	public void setHidemode(boolean hidemode) {
		this.hidemode = hidemode;
	}

	public Integer getAreaItemLevel() {
		return this.areaItemLevel;
	}

	public void setAreaItemLevel(Integer areaItemLevel) {
		this.areaItemLevel = areaItemLevel;
	}

	public String getNpcs() {
		return this.npcs;
	}

	public void setNpcs(String npcs) {
		this.npcs = npcs;
	}

	public Set<Player> getPlayers() {
		return this.players;
	}

	public void setPlayers(Set<Player> players) {
		this.players = players;
	}

}
