package org.infinite.db.dao;

// Generated 15-mar-2009 21.16.44 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private Integer id;
	private Locks locks;
	private String name;
	private String description;
	private Integer world;
	private Integer nx;
	private Integer ny;
	private Integer cost;
	private Set<Player> players = new HashSet<Player>(0);
	private Set<AreaItem> areaItems = new HashSet<AreaItem>(0);

	public Area() {
	}

	public Area(Locks locks, String name, String description, Integer world,
			Integer nx, Integer ny, Integer cost) {
		this.locks = locks;
		this.name = name;
		this.description = description;
		this.world = world;
		this.nx = nx;
		this.ny = ny;
		this.cost = cost;
	}

	public Area(Locks locks, String name, String description, Integer world,
			Integer nx, Integer ny, Integer cost, Set<Player> players,
			Set<AreaItem> areaItems) {
		this.locks = locks;
		this.name = name;
		this.description = description;
		this.world = world;
		this.nx = nx;
		this.ny = ny;
		this.cost = cost;
		this.players = players;
		this.areaItems = areaItems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Locks getLocks() {
		return this.locks;
	}

	public void setLocks(Locks locks) {
		this.locks = locks;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getWorld() {
		return this.world;
	}

	public void setWorld(Integer world) {
		this.world = world;
	}

	public Integer getNx() {
		return this.nx;
	}

	public void setNx(Integer nx) {
		this.nx = nx;
	}

	public Integer getNy() {
		return this.ny;
	}

	public void setNy(Integer ny) {
		this.ny = ny;
	}

	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	public Set<Player> getPlayers() {
		return this.players;
	}

	public void setPlayers(Set<Player> players) {
		this.players = players;
	}

	public Set<AreaItem> getAreaItems() {
		return this.areaItems;
	}

	public void setAreaItems(Set<AreaItem> areaItems) {
		this.areaItems = areaItems;
	}

}
