package org.infinite.db.dao;

// Generated 23-feb-2009 21.37.11 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private Integer id;
	private Spell spell;
	private String name;
	private String descr;
	private String image;
	private int costAp;
	private int reqStr;
	private int reqInt;
	private int reqWis;
	private int reqDex;
	private int reqCha;
	private int reqLev;
	private int modStr;
	private int modInt;
	private int modWis;
	private int modDex;
	private int modCha;
	private float price;
	private int lev;
	private String damage;
	private int initiative;
	private int durability;
	private int type;
	private Set playerOwnItems = new HashSet(0);

	public Item() {
	}

	public Item(Spell spell, String name, String descr, String image,
			int costAp, int reqStr, int reqInt, int reqWis, int reqDex,
			int reqCha, int reqLev, int modStr, int modInt, int modWis,
			int modDex, int modCha, float price, int lev, String damage,
			int initiative, int durability, int type) {
		this.spell = spell;
		this.name = name;
		this.descr = descr;
		this.image = image;
		this.costAp = costAp;
		this.reqStr = reqStr;
		this.reqInt = reqInt;
		this.reqWis = reqWis;
		this.reqDex = reqDex;
		this.reqCha = reqCha;
		this.reqLev = reqLev;
		this.modStr = modStr;
		this.modInt = modInt;
		this.modWis = modWis;
		this.modDex = modDex;
		this.modCha = modCha;
		this.price = price;
		this.lev = lev;
		this.damage = damage;
		this.initiative = initiative;
		this.durability = durability;
		this.type = type;
	}

	public Item(Spell spell, String name, String descr, String image,
			int costAp, int reqStr, int reqInt, int reqWis, int reqDex,
			int reqCha, int reqLev, int modStr, int modInt, int modWis,
			int modDex, int modCha, float price, int lev, String damage,
			int initiative, int durability, int type, Set playerOwnItems) {
		this.spell = spell;
		this.name = name;
		this.descr = descr;
		this.image = image;
		this.costAp = costAp;
		this.reqStr = reqStr;
		this.reqInt = reqInt;
		this.reqWis = reqWis;
		this.reqDex = reqDex;
		this.reqCha = reqCha;
		this.reqLev = reqLev;
		this.modStr = modStr;
		this.modInt = modInt;
		this.modWis = modWis;
		this.modDex = modDex;
		this.modCha = modCha;
		this.price = price;
		this.lev = lev;
		this.damage = damage;
		this.initiative = initiative;
		this.durability = durability;
		this.type = type;
		this.playerOwnItems = playerOwnItems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Spell getSpell() {
		return this.spell;
	}

	public void setSpell(Spell spell) {
		this.spell = spell;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public int getCostAp() {
		return this.costAp;
	}

	public void setCostAp(int costAp) {
		this.costAp = costAp;
	}

	public int getReqStr() {
		return this.reqStr;
	}

	public void setReqStr(int reqStr) {
		this.reqStr = reqStr;
	}

	public int getReqInt() {
		return this.reqInt;
	}

	public void setReqInt(int reqInt) {
		this.reqInt = reqInt;
	}

	public int getReqWis() {
		return this.reqWis;
	}

	public void setReqWis(int reqWis) {
		this.reqWis = reqWis;
	}

	public int getReqDex() {
		return this.reqDex;
	}

	public void setReqDex(int reqDex) {
		this.reqDex = reqDex;
	}

	public int getReqCha() {
		return this.reqCha;
	}

	public void setReqCha(int reqCha) {
		this.reqCha = reqCha;
	}

	public int getReqLev() {
		return this.reqLev;
	}

	public void setReqLev(int reqLev) {
		this.reqLev = reqLev;
	}

	public int getModStr() {
		return this.modStr;
	}

	public void setModStr(int modStr) {
		this.modStr = modStr;
	}

	public int getModInt() {
		return this.modInt;
	}

	public void setModInt(int modInt) {
		this.modInt = modInt;
	}

	public int getModWis() {
		return this.modWis;
	}

	public void setModWis(int modWis) {
		this.modWis = modWis;
	}

	public int getModDex() {
		return this.modDex;
	}

	public void setModDex(int modDex) {
		this.modDex = modDex;
	}

	public int getModCha() {
		return this.modCha;
	}

	public void setModCha(int modCha) {
		this.modCha = modCha;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public int getLev() {
		return this.lev;
	}

	public void setLev(int lev) {
		this.lev = lev;
	}

	public String getDamage() {
		return this.damage;
	}

	public void setDamage(String damage) {
		this.damage = damage;
	}

	public int getInitiative() {
		return this.initiative;
	}

	public void setInitiative(int initiative) {
		this.initiative = initiative;
	}

	public int getDurability() {
		return this.durability;
	}

	public void setDurability(int durability) {
		this.durability = durability;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public Set getPlayerOwnItems() {
		return this.playerOwnItems;
	}

	public void setPlayerOwnItems(Set playerOwnItems) {
		this.playerOwnItems = playerOwnItems;
	}

}
