package org.infinite.db.dao;

// Generated 10-mag-2009 10.46.59 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Locks generated by hbm2java
 */
public class Locks implements java.io.Serializable {

	private Integer id;
	private Locks locks;
	private String name;
	private Set<Area> areas = new HashSet<Area>(0);
	private Set<Locks> lockses = new HashSet<Locks>(0);

	public Locks() {
	}

	public Locks(String name) {
		this.name = name;
	}

	public Locks(Locks locks, String name, Set<Area> areas, Set<Locks> lockses) {
		this.locks = locks;
		this.name = name;
		this.areas = areas;
		this.lockses = lockses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Locks getLocks() {
		return this.locks;
	}

	public void setLocks(Locks locks) {
		this.locks = locks;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

	public Set<Locks> getLockses() {
		return this.lockses;
	}

	public void setLockses(Set<Locks> lockses) {
		this.lockses = lockses;
	}

}
