package org.infinite.db.dao;

// Generated 19-mar-2009 18.12.08 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Locks generated by hbm2java
 */
public class Locks implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer parentId;
	private Set<AreaItem> areaItems = new HashSet<AreaItem>(0);
	private Set<Area> areas = new HashSet<Area>(0);

	public Locks() {
	}

	public Locks(String name) {
		this.name = name;
	}

	public Locks(String name, Integer parentId, Set<AreaItem> areaItems,
			Set<Area> areas) {
		this.name = name;
		this.parentId = parentId;
		this.areaItems = areaItems;
		this.areas = areas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Set<AreaItem> getAreaItems() {
		return this.areaItems;
	}

	public void setAreaItems(Set<AreaItem> areaItems) {
		this.areaItems = areaItems;
	}

	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

}
