package org.infinite.db.dao;

// Generated 27-feb-2009 22.51.40 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Locks generated by hbm2java
 */
public class Locks implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer parentId;
	private Set areas = new HashSet(0);

	public Locks() {
	}

	public Locks(String name) {
		this.name = name;
	}

	public Locks(String name, Integer parentId, Set areas) {
		this.name = name;
		this.parentId = parentId;
		this.areas = areas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Set getAreas() {
		return this.areas;
	}

	public void setAreas(Set areas) {
		this.areas = areas;
	}

}
