package org.infinite.db.dao;

// Generated 23-feb-2009 21.37.11 by Hibernate Tools 3.2.2.GA

/**
 * Npc generated by hbm2java
 */
public class Npc implements java.io.Serializable {

	private int id;
	private String name;
	private String image;
	private String description;
	private int baseStr;
	private int baseInt;
	private int baseDex;
	private int baseCha;
	private int basePl;
	private int basePm;
	private int basePa;
	private int basePc;
	private int level;
	private int px;
	private int status;
	private int area;
	private float gold;
	private String xmlDialog;
	private String xmlItems;
	private String xmlBehave;
	private boolean ismonster;
	private int nattack;
	private String attack;

	public Npc() {
	}

	public Npc(int id, String name, String image, String description,
			int baseStr, int baseInt, int baseDex, int baseCha, int basePl,
			int basePm, int basePa, int basePc, int level, int px, int status,
			int area, float gold, String xmlDialog, String xmlItems,
			String xmlBehave, boolean ismonster, int nattack, String attack) {
		this.id = id;
		this.name = name;
		this.image = image;
		this.description = description;
		this.baseStr = baseStr;
		this.baseInt = baseInt;
		this.baseDex = baseDex;
		this.baseCha = baseCha;
		this.basePl = basePl;
		this.basePm = basePm;
		this.basePa = basePa;
		this.basePc = basePc;
		this.level = level;
		this.px = px;
		this.status = status;
		this.area = area;
		this.gold = gold;
		this.xmlDialog = xmlDialog;
		this.xmlItems = xmlItems;
		this.xmlBehave = xmlBehave;
		this.ismonster = ismonster;
		this.nattack = nattack;
		this.attack = attack;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getBaseStr() {
		return this.baseStr;
	}

	public void setBaseStr(int baseStr) {
		this.baseStr = baseStr;
	}

	public int getBaseInt() {
		return this.baseInt;
	}

	public void setBaseInt(int baseInt) {
		this.baseInt = baseInt;
	}

	public int getBaseDex() {
		return this.baseDex;
	}

	public void setBaseDex(int baseDex) {
		this.baseDex = baseDex;
	}

	public int getBaseCha() {
		return this.baseCha;
	}

	public void setBaseCha(int baseCha) {
		this.baseCha = baseCha;
	}

	public int getBasePl() {
		return this.basePl;
	}

	public void setBasePl(int basePl) {
		this.basePl = basePl;
	}

	public int getBasePm() {
		return this.basePm;
	}

	public void setBasePm(int basePm) {
		this.basePm = basePm;
	}

	public int getBasePa() {
		return this.basePa;
	}

	public void setBasePa(int basePa) {
		this.basePa = basePa;
	}

	public int getBasePc() {
		return this.basePc;
	}

	public void setBasePc(int basePc) {
		this.basePc = basePc;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getPx() {
		return this.px;
	}

	public void setPx(int px) {
		this.px = px;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	public float getGold() {
		return this.gold;
	}

	public void setGold(float gold) {
		this.gold = gold;
	}

	public String getXmlDialog() {
		return this.xmlDialog;
	}

	public void setXmlDialog(String xmlDialog) {
		this.xmlDialog = xmlDialog;
	}

	public String getXmlItems() {
		return this.xmlItems;
	}

	public void setXmlItems(String xmlItems) {
		this.xmlItems = xmlItems;
	}

	public String getXmlBehave() {
		return this.xmlBehave;
	}

	public void setXmlBehave(String xmlBehave) {
		this.xmlBehave = xmlBehave;
	}

	public boolean isIsmonster() {
		return this.ismonster;
	}

	public void setIsmonster(boolean ismonster) {
		this.ismonster = ismonster;
	}

	public int getNattack() {
		return this.nattack;
	}

	public void setNattack(int nattack) {
		this.nattack = nattack;
	}

	public String getAttack() {
		return this.attack;
	}

	public void setAttack(String attack) {
		this.attack = attack;
	}

}
