package org.infinite.db.dao;

// Generated 19-feb-2009 22.03.23 by Hibernate Tools 3.2.2.GA

/**
 * NpcOwnItemId generated by hbm2java
 */
public class NpcOwnItemId implements java.io.Serializable {

	private int npcid;
	private int itemid;

	public NpcOwnItemId() {
	}

	public NpcOwnItemId(int npcid, int itemid) {
		this.npcid = npcid;
		this.itemid = itemid;
	}

	public int getNpcid() {
		return this.npcid;
	}

	public void setNpcid(int npcid) {
		this.npcid = npcid;
	}

	public int getItemid() {
		return this.itemid;
	}

	public void setItemid(int itemid) {
		this.itemid = itemid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NpcOwnItemId))
			return false;
		NpcOwnItemId castOther = (NpcOwnItemId) other;

		return (this.getNpcid() == castOther.getNpcid())
				&& (this.getItemid() == castOther.getItemid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNpcid();
		result = 37 * result + this.getItemid();
		return result;
	}

}
