package org.infinite.db.dao;

// Generated 19-feb-2009 22.03.23 by Hibernate Tools 3.2.2.GA

/**
 * NpcOwnItem generated by hbm2java
 */
public class NpcOwnItem implements java.io.Serializable {

	private NpcOwnItemId id;
	private int status;
	private int bodypart;

	public NpcOwnItem() {
	}

	public NpcOwnItem(NpcOwnItemId id, int status, int bodypart) {
		this.id = id;
		this.status = status;
		this.bodypart = bodypart;
	}

	public NpcOwnItemId getId() {
		return this.id;
	}

	public void setId(NpcOwnItemId id) {
		this.id = id;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getBodypart() {
		return this.bodypart;
	}

	public void setBodypart(int bodypart) {
		this.bodypart = bodypart;
	}

}
