package org.infinite.db.dao;

// Generated 19-feb-2009 22.03.23 by Hibernate Tools 3.2.2.GA

/**
 * PlayerKnowSpell generated by hbm2java
 */
public class PlayerKnowSpell implements java.io.Serializable {

	private PlayerKnowSpellId id;

	public PlayerKnowSpell() {
	}

	public PlayerKnowSpell(PlayerKnowSpellId id) {
		this.id = id;
	}

	public PlayerKnowSpellId getId() {
		return this.id;
	}

	public void setId(PlayerKnowSpellId id) {
		this.id = id;
	}

}
