package org.infinite.db.dao;

// Generated 27-feb-2009 22.51.40 by Hibernate Tools 3.2.2.GA

/**
 * PlayerOwnItemId generated by hbm2java
 */
public class PlayerOwnItemId implements java.io.Serializable {

	private int playerid;
	private int itemid;

	public PlayerOwnItemId() {
	}

	public PlayerOwnItemId(int playerid, int itemid) {
		this.playerid = playerid;
		this.itemid = itemid;
	}

	public int getPlayerid() {
		return this.playerid;
	}

	public void setPlayerid(int playerid) {
		this.playerid = playerid;
	}

	public int getItemid() {
		return this.itemid;
	}

	public void setItemid(int itemid) {
		this.itemid = itemid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlayerOwnItemId))
			return false;
		PlayerOwnItemId castOther = (PlayerOwnItemId) other;

		return (this.getPlayerid() == castOther.getPlayerid())
				&& (this.getItemid() == castOther.getItemid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlayerid();
		result = 37 * result + this.getItemid();
		return result;
	}

}
