package org.infinite.db.dao;

// Generated 15-mar-2009 21.16.44 by Hibernate Tools 3.2.4.CR1

/**
 * PlayerOwnItem generated by hbm2java
 */
public class PlayerOwnItem implements java.io.Serializable {

	private Integer id;
	private Player player;
	private Item item;
	private Integer status;
	private Integer bodypart;

	public PlayerOwnItem() {
	}

	public PlayerOwnItem(Player player, Item item, Integer status,
			Integer bodypart) {
		this.player = player;
		this.item = item;
		this.status = status;
		this.bodypart = bodypart;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getBodypart() {
		return this.bodypart;
	}

	public void setBodypart(Integer bodypart) {
		this.bodypart = bodypart;
	}

}
