package org.infinite.db.dao;

// Generated 8-mar-2009 23.42.10 by Hibernate Tools 3.2.4.CR1

/**
 * PlayerOwnItemId generated by hbm2java
 */
public class PlayerOwnItemId implements java.io.Serializable {

	private Integer playerid;
	private Integer itemid;

	public PlayerOwnItemId() {
	}

	public PlayerOwnItemId(Integer playerid, Integer itemid) {
		this.playerid = playerid;
		this.itemid = itemid;
	}

	public Integer getPlayerid() {
		return this.playerid;
	}

	public void setPlayerid(Integer playerid) {
		this.playerid = playerid;
	}

	public Integer getItemid() {
		return this.itemid;
	}

	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlayerOwnItemId))
			return false;
		PlayerOwnItemId castOther = (PlayerOwnItemId) other;

		return ((this.getPlayerid() == castOther.getPlayerid()) || (this
				.getPlayerid() != null
				&& castOther.getPlayerid() != null && this.getPlayerid()
				.equals(castOther.getPlayerid())))
				&& ((this.getItemid() == castOther.getItemid()) || (this
						.getItemid() != null
						&& castOther.getItemid() != null && this.getItemid()
						.equals(castOther.getItemid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPlayerid() == null ? 0 : this.getPlayerid().hashCode());
		result = 37 * result
				+ (getItemid() == null ? 0 : this.getItemid().hashCode());
		return result;
	}

}
