package org.infinite.db.dao;

// Generated 27-feb-2009 22.51.40 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Player generated by hbm2java
 */
public class Player implements java.io.Serializable {

	private int id;
	private TomcatUsers tomcatUsers;
	private Area area;
	private String name;
	private String image;
	private int baseStr;
	private int baseInt;
	private int baseDex;
	private int baseCha;
	private int basePl;
	private int basePm;
	private int basePa;
	private int basePc;
	private int level;
	private int px;
	private int status;
	private float gold;
	private int nattack;
	private String attack;
	private Set playerOwnItems = new HashSet(0);
	private Set spells = new HashSet(0);
	private Set spells_1 = new HashSet(0);

	public Player() {
	}

	public Player(int id, TomcatUsers tomcatUsers, Area area, String name,
			String image, int baseStr, int baseInt, int baseDex, int baseCha,
			int basePl, int basePm, int basePa, int basePc, int level, int px,
			int status, float gold, int nattack) {
		this.id = id;
		this.tomcatUsers = tomcatUsers;
		this.area = area;
		this.name = name;
		this.image = image;
		this.baseStr = baseStr;
		this.baseInt = baseInt;
		this.baseDex = baseDex;
		this.baseCha = baseCha;
		this.basePl = basePl;
		this.basePm = basePm;
		this.basePa = basePa;
		this.basePc = basePc;
		this.level = level;
		this.px = px;
		this.status = status;
		this.gold = gold;
		this.nattack = nattack;
	}

	public Player(int id, TomcatUsers tomcatUsers, Area area, String name,
			String image, int baseStr, int baseInt, int baseDex, int baseCha,
			int basePl, int basePm, int basePa, int basePc, int level, int px,
			int status, float gold, int nattack, String attack,
			Set playerOwnItems, Set spells, Set spells_1) {
		this.id = id;
		this.tomcatUsers = tomcatUsers;
		this.area = area;
		this.name = name;
		this.image = image;
		this.baseStr = baseStr;
		this.baseInt = baseInt;
		this.baseDex = baseDex;
		this.baseCha = baseCha;
		this.basePl = basePl;
		this.basePm = basePm;
		this.basePa = basePa;
		this.basePc = basePc;
		this.level = level;
		this.px = px;
		this.status = status;
		this.gold = gold;
		this.nattack = nattack;
		this.attack = attack;
		this.playerOwnItems = playerOwnItems;
		this.spells = spells;
		this.spells_1 = spells_1;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TomcatUsers getTomcatUsers() {
		return this.tomcatUsers;
	}

	public void setTomcatUsers(TomcatUsers tomcatUsers) {
		this.tomcatUsers = tomcatUsers;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public int getBaseStr() {
		return this.baseStr;
	}

	public void setBaseStr(int baseStr) {
		this.baseStr = baseStr;
	}

	public int getBaseInt() {
		return this.baseInt;
	}

	public void setBaseInt(int baseInt) {
		this.baseInt = baseInt;
	}

	public int getBaseDex() {
		return this.baseDex;
	}

	public void setBaseDex(int baseDex) {
		this.baseDex = baseDex;
	}

	public int getBaseCha() {
		return this.baseCha;
	}

	public void setBaseCha(int baseCha) {
		this.baseCha = baseCha;
	}

	public int getBasePl() {
		return this.basePl;
	}

	public void setBasePl(int basePl) {
		this.basePl = basePl;
	}

	public int getBasePm() {
		return this.basePm;
	}

	public void setBasePm(int basePm) {
		this.basePm = basePm;
	}

	public int getBasePa() {
		return this.basePa;
	}

	public void setBasePa(int basePa) {
		this.basePa = basePa;
	}

	public int getBasePc() {
		return this.basePc;
	}

	public void setBasePc(int basePc) {
		this.basePc = basePc;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getPx() {
		return this.px;
	}

	public void setPx(int px) {
		this.px = px;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public float getGold() {
		return this.gold;
	}

	public void setGold(float gold) {
		this.gold = gold;
	}

	public int getNattack() {
		return this.nattack;
	}

	public void setNattack(int nattack) {
		this.nattack = nattack;
	}

	public String getAttack() {
		return this.attack;
	}

	public void setAttack(String attack) {
		this.attack = attack;
	}

	public Set getPlayerOwnItems() {
		return this.playerOwnItems;
	}

	public void setPlayerOwnItems(Set playerOwnItems) {
		this.playerOwnItems = playerOwnItems;
	}

	public Set getSpells() {
		return this.spells;
	}

	public void setSpells(Set spells) {
		this.spells = spells;
	}

	public Set getSpells_1() {
		return this.spells_1;
	}

	public void setSpells_1(Set spells_1) {
		this.spells_1 = spells_1;
	}

}
