package org.infinite.db.dao;

// Generated 8-mar-2009 23.42.10 by Hibernate Tools 3.2.4.CR1

/**
 * PlayerOwnItem generated by hbm2java
 */
public class PlayerOwnItem implements java.io.Serializable {

	private PlayerOwnItemId id;
	private Player player;
	private Item item;
	private Integer status;
	private Integer bodypart;

	public PlayerOwnItem() {
	}

	public PlayerOwnItem(PlayerOwnItemId id, Player player, Item item,
			Integer status, Integer bodypart) {
		this.id = id;
		this.player = player;
		this.item = item;
		this.status = status;
		this.bodypart = bodypart;
	}

	public PlayerOwnItemId getId() {
		return this.id;
	}

	public void setId(PlayerOwnItemId id) {
		this.id = id;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getBodypart() {
		return this.bodypart;
	}

	public void setBodypart(Integer bodypart) {
		this.bodypart = bodypart;
	}

}
