package org.infinite.db.dao;

// Generated 5-mag-2009 22.23.06 by Hibernate Tools 3.2.4.CR1

/**
 * SpellAffectPlayer generated by hbm2java
 */
public class SpellAffectPlayer implements java.io.Serializable {

	private Integer id;
	private Player player;
	private Spell spell;
	private long elapsing;

	public SpellAffectPlayer() {
	}

	public SpellAffectPlayer(Player player, Spell spell, long elapsing) {
		this.player = player;
		this.spell = spell;
		this.elapsing = elapsing;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public Spell getSpell() {
		return this.spell;
	}

	public void setSpell(Spell spell) {
		this.spell = spell;
	}

	public long getElapsing() {
		return this.elapsing;
	}

	public void setElapsing(long elapsing) {
		this.elapsing = elapsing;
	}

}
