package org.infinite.db.dao;

// Generated 31-mar-2009 0.21.58 by Hibernate Tools 3.2.4.CR1

/**
 * SpellAffectPlayer generated by hbm2java
 */
public class SpellAffectPlayer implements java.io.Serializable {

	private SpellAffectPlayerId id;

	public SpellAffectPlayer() {
	}

	public SpellAffectPlayer(SpellAffectPlayerId id) {
		this.id = id;
	}

	public SpellAffectPlayerId getId() {
		return this.id;
	}

	public void setId(SpellAffectPlayerId id) {
		this.id = id;
	}

}
