package org.infinite.db.dao;

// Generated 31-mar-2009 0.21.58 by Hibernate Tools 3.2.4.CR1

/**
 * SpellAffectPlayerId generated by hbm2java
 */
public class SpellAffectPlayerId implements java.io.Serializable {

	private Integer playerid;
	private Integer spellid;

	public SpellAffectPlayerId() {
	}

	public SpellAffectPlayerId(Integer playerid, Integer spellid) {
		this.playerid = playerid;
		this.spellid = spellid;
	}

	public Integer getPlayerid() {
		return this.playerid;
	}

	public void setPlayerid(Integer playerid) {
		this.playerid = playerid;
	}

	public Integer getSpellid() {
		return this.spellid;
	}

	public void setSpellid(Integer spellid) {
		this.spellid = spellid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpellAffectPlayerId))
			return false;
		SpellAffectPlayerId castOther = (SpellAffectPlayerId) other;

		return ((this.getPlayerid() == castOther.getPlayerid()) || (this
				.getPlayerid() != null
				&& castOther.getPlayerid() != null && this.getPlayerid()
				.equals(castOther.getPlayerid())))
				&& ((this.getSpellid() == castOther.getSpellid()) || (this
						.getSpellid() != null
						&& castOther.getSpellid() != null && this.getSpellid()
						.equals(castOther.getSpellid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPlayerid() == null ? 0 : this.getPlayerid().hashCode());
		result = 37 * result
				+ (getSpellid() == null ? 0 : this.getSpellid().hashCode());
		return result;
	}

}
