package org.infinite.db.dao;

// Generated 27-feb-2009 22.51.40 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Spell generated by hbm2java
 */
public class Spell implements java.io.Serializable {

	private Integer id;
	private String name;
	private String desc;
	private String image;
	private int costMp;
	private int reqStr;
	private int reqInt;
	private int reqWis;
	private int reqDex;
	private int reqCha;
	private int reqLev;
	private int modStr;
	private int modInt;
	private int modWis;
	private int modDex;
	private int modCha;
	private float price;
	private int lev;
	private int duration;
	private int spelltype;
	private String damage;
	private int savingthrow;
	private int initiative;
	private Set players = new HashSet(0);
	private Set items = new HashSet(0);
	private Set players_1 = new HashSet(0);

	public Spell() {
	}

	public Spell(String name, String desc, String image, int costMp,
			int reqStr, int reqInt, int reqWis, int reqDex, int reqCha,
			int reqLev, int modStr, int modInt, int modWis, int modDex,
			int modCha, float price, int lev, int duration, int spelltype,
			String damage, int savingthrow, int initiative) {
		this.name = name;
		this.desc = desc;
		this.image = image;
		this.costMp = costMp;
		this.reqStr = reqStr;
		this.reqInt = reqInt;
		this.reqWis = reqWis;
		this.reqDex = reqDex;
		this.reqCha = reqCha;
		this.reqLev = reqLev;
		this.modStr = modStr;
		this.modInt = modInt;
		this.modWis = modWis;
		this.modDex = modDex;
		this.modCha = modCha;
		this.price = price;
		this.lev = lev;
		this.duration = duration;
		this.spelltype = spelltype;
		this.damage = damage;
		this.savingthrow = savingthrow;
		this.initiative = initiative;
	}

	public Spell(String name, String desc, String image, int costMp,
			int reqStr, int reqInt, int reqWis, int reqDex, int reqCha,
			int reqLev, int modStr, int modInt, int modWis, int modDex,
			int modCha, float price, int lev, int duration, int spelltype,
			String damage, int savingthrow, int initiative, Set players,
			Set items, Set players_1) {
		this.name = name;
		this.desc = desc;
		this.image = image;
		this.costMp = costMp;
		this.reqStr = reqStr;
		this.reqInt = reqInt;
		this.reqWis = reqWis;
		this.reqDex = reqDex;
		this.reqCha = reqCha;
		this.reqLev = reqLev;
		this.modStr = modStr;
		this.modInt = modInt;
		this.modWis = modWis;
		this.modDex = modDex;
		this.modCha = modCha;
		this.price = price;
		this.lev = lev;
		this.duration = duration;
		this.spelltype = spelltype;
		this.damage = damage;
		this.savingthrow = savingthrow;
		this.initiative = initiative;
		this.players = players;
		this.items = items;
		this.players_1 = players_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public int getCostMp() {
		return this.costMp;
	}

	public void setCostMp(int costMp) {
		this.costMp = costMp;
	}

	public int getReqStr() {
		return this.reqStr;
	}

	public void setReqStr(int reqStr) {
		this.reqStr = reqStr;
	}

	public int getReqInt() {
		return this.reqInt;
	}

	public void setReqInt(int reqInt) {
		this.reqInt = reqInt;
	}

	public int getReqWis() {
		return this.reqWis;
	}

	public void setReqWis(int reqWis) {
		this.reqWis = reqWis;
	}

	public int getReqDex() {
		return this.reqDex;
	}

	public void setReqDex(int reqDex) {
		this.reqDex = reqDex;
	}

	public int getReqCha() {
		return this.reqCha;
	}

	public void setReqCha(int reqCha) {
		this.reqCha = reqCha;
	}

	public int getReqLev() {
		return this.reqLev;
	}

	public void setReqLev(int reqLev) {
		this.reqLev = reqLev;
	}

	public int getModStr() {
		return this.modStr;
	}

	public void setModStr(int modStr) {
		this.modStr = modStr;
	}

	public int getModInt() {
		return this.modInt;
	}

	public void setModInt(int modInt) {
		this.modInt = modInt;
	}

	public int getModWis() {
		return this.modWis;
	}

	public void setModWis(int modWis) {
		this.modWis = modWis;
	}

	public int getModDex() {
		return this.modDex;
	}

	public void setModDex(int modDex) {
		this.modDex = modDex;
	}

	public int getModCha() {
		return this.modCha;
	}

	public void setModCha(int modCha) {
		this.modCha = modCha;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public int getLev() {
		return this.lev;
	}

	public void setLev(int lev) {
		this.lev = lev;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public int getSpelltype() {
		return this.spelltype;
	}

	public void setSpelltype(int spelltype) {
		this.spelltype = spelltype;
	}

	public String getDamage() {
		return this.damage;
	}

	public void setDamage(String damage) {
		this.damage = damage;
	}

	public int getSavingthrow() {
		return this.savingthrow;
	}

	public void setSavingthrow(int savingthrow) {
		this.savingthrow = savingthrow;
	}

	public int getInitiative() {
		return this.initiative;
	}

	public void setInitiative(int initiative) {
		this.initiative = initiative;
	}

	public Set getPlayers() {
		return this.players;
	}

	public void setPlayers(Set players) {
		this.players = players;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

	public Set getPlayers_1() {
		return this.players_1;
	}

	public void setPlayers_1(Set players_1) {
		this.players_1 = players_1;
	}

}
