package org.infinite.db.dao;

// Generated 19-feb-2009 22.03.23 by Hibernate Tools 3.2.2.GA

/**
 * SpellAffectPlayer generated by hbm2java
 */
public class SpellAffectPlayer implements java.io.Serializable {

	private SpellAffectPlayerId id;

	public SpellAffectPlayer() {
	}

	public SpellAffectPlayer(SpellAffectPlayerId id) {
		this.id = id;
	}

	public SpellAffectPlayerId getId() {
		return this.id;
	}

	public void setId(SpellAffectPlayerId id) {
		this.id = id;
	}

}
