package org.infinite.db.dao;

// Generated 23-feb-2009 21.36.03 by Hibernate Tools 3.2.2.GA

/**
 * TomcatRolesId generated by hbm2java
 */
public class TomcatRolesId implements java.io.Serializable {

	private String user;
	private String role;

	public TomcatRolesId() {
	}

	public TomcatRolesId(String user, String role) {
		this.user = user;
		this.role = role;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TomcatRolesId))
			return false;
		TomcatRolesId castOther = (TomcatRolesId) other;

		return ((this.getUser() == castOther.getUser()) || (this.getUser() != null
				&& castOther.getUser() != null && this.getUser().equals(
				castOther.getUser())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null
						&& castOther.getRole() != null && this.getRole()
						.equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUser() == null ? 0 : this.getUser().hashCode());
		result = 37 * result
				+ (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
