-- phpMyAdmin SQL Dump
-- version 2.11.9.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generato il: 05 Mag, 2009 at 03:00 PM
-- Versione MySQL: 5.0.67
-- Versione PHP: 5.2.4

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `mikesac_mikesac`
--

--
-- Dump dei dati per la tabella `NPC`
--

INSERT INTO `NPC` (`id`, `name`, `image`, `description`, `base_str`, `base_int`, `base_dex`, `base_cha`, `base_pl`, `base_pm`, `base_pa`, `base_pc`, `level`, `px`, `status`, `area`, `gold`, `xml_dialog`, `xml_items`, `xml_behave`, `ismonster`, `nattack`, `attack`) VALUES
(1, 'Goblin', 'goblin', 'Goblins are small humanoid monsters. They vary in height from about 3 to 3 ½ feet (91 - 106 cm) and weigh 40 to 45 pounds (21 - 24 kg). They walk upright even though their arms nearly reach their knees. Their eyes vary from red to yellow and are usually dull and glazed. They have a broad nose that sits on a flat face with pointed ears and a wide mouth. Their mouth contains small, but sharp fangs. Their skin pigment ranges from a deep red through nearly any shade of orange to yellow. Members of the same tribe tend to have the same skin color. Based on their ability scores and the encumbrance rules the average goblin would be able to lift about 60 pounds over his head.', 5, 5, 5, 5, 12, 6, 10, 5, 1, 10, 0, 1, 1, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'Unarmed,1d1'),
(2, 'Hobgoblin', 'hobgoblin', 'Hobgoblins exist in perpetual war against all other races, believing that "lesser" species are fit only for battle fodder. In mixed groups, hobgoblin officers often lead units of goblins or orcs, whom they bully and make to feel inferior. Other peoples find them paranoid, insulting, and dismissive, while hobgoblins in turn treat all others as potential threats. Hobgoblin mercenaries may offer their services to powerful and wealthy members of other races, however.', 5, 5, 5, 5, 12, 6, 10, 5, 1, 10, 0, 1, 1, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'Unarmed,1d1'),
(3, 'Actaeon', 'Actaeon', 'This solitary creature is a protector of woodland\r\ncreatures. The actaeon is 9'' tall, with the\r\narms, torso, and facial features of a human but\r\nthe antlers and lower legs of an elk; its whole\r\nbody is covered with brown elklike hide.Actaeons are members of the woodland community\r\nalong with centaurs, dryads, etc. They\r\nare sufficiently bold and rare that they are renowned\r\nheroes of these forest folk. Actaeon\r\nsometimes work with druids to preserve the\r\nsafety of the woods, especially if a dangerous\r\nthreat is involved.', 16, 12, 12, 7, 108, 56, 66, 45, 11, 2200, 0, 1, 500, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, 'spear,1d6 + 6/breath, 1d6 + 6'),
(4, 'Adaptor', 'Adaptor', 'Adaptors are a peculiar race native to all\r\nplanes of existence. They are very intelligent,\r\nand their ancient race has greater and wider\r\nknowledge than any sage, but their cultural philosophy\r\ndemands that they not pass their great\r\nknowledge between planes and human cultures.\r\nInstead, they travel and observe civilization\r\nthroughout the planes, exchanging information\r\nonly among themselves.', 12, 14, 10, 9, 79, 72, 46, 48, 8, 1100, 0, 1, 125, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, 'weapon,1d8 + 4 /weapon,1d8 + 4'),
(5, 'Aerial Servant', 'Aerialser', 'Aerial servants are humanoid in shape. They\r\nappear to be man-shaped figures of roiling fog;\r\nthey are eerie and menacing.\r\nAerial servants are beings native to the elemental\r\nplane of Air. On their home plane, they\r\nare known by a name which sounds like\r\n"haoou.', 10, 12, 13, 9, 128, 96, 143, 96, 16, 3890, 0, 1, 800, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'special,4d8'),
(6, 'Sheep', 'Sheep', 'This common animal are often in herd.', 6, 6, 6, 5, 16, 10, 10, 10, 2, 25, 0, 2, 15, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'kick,1d6'),
(7, 'Ant, Giant', 'antg', 'Giant ants are black ants about 6'' long. They are\r\nomnivores and will attack anything edible that lies\r\nin their path (no reaction roll); if they win, they carry\r\ntheir kills back to the nest. Once engaged in\r\ncombat, they will fight to the death, even trying to\r\ncross flames to reach their opponents.\r\nA giant ant nest looks like a large, bare hill.\r\nGiant ant nests are not as heavily populated as\r\nthose of smaller ants.', 3, 3, 9, 4, 27, 10, 22, 14, 4, 125, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite,2d6'),
(8, 'Ape, Snow', 'apeg', 'Snow apes are squat, baboonlike creatures\r\nwith shaggy white fur. They are somewhat intelligent,\r\nand often make simple tools like clubs or\r\nsharpened bones. They cannot, however, grasp\r\nmore complicated concepts, such as the use of a\r\nbow and arrow.', 3, 4, 9, 4, 22, 13, 11, 9, 4, 75, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'hug,1d8+1'),
(9, 'Ape, White', 'apew', 'White apes have lost their color due to many\r\nyears of living in caves. They are nocturnal herbivores,\r\nlooking for fruits and vegetables at\r\nnight.\r\nThey do not go out of their way to attack characters;\r\nif approached by humans and demihumans\r\nand given a chance to flee, they will do\r\nso. But if creatures approach their lair, the apes\r\nwill threaten the intruders. If their threats are ignored,\r\nthey will attack', 3, 2, 8, 3, 22, 10, 15, 9, 4, 75, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, 'clow,1d4/rock, 1d4'),
(10, 'Bandit', 'Bandit', 'It''s like a human thief how lives in town or in the wood.', 10, 11, 10, 10, 11, 6, 6, 6, 1, 10, 0, 1, 10, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'weapon,1d6'),
(11, 'Basilisk', 'Basilisk', 'A basilisk is a 10''-long lizard; it looks much\r\nlike a large snake with four legs and a crownlike\r\ngrowth on its head. It may be of any color, but is\r\nusually very bright and distinctive. It is sometimes\r\ncalled the "king of snakes."\r\nThe basilisk is a nonintelligent but very magical\r\nlizard. It lives in underground caverns or wild\r\nand tangled thickets. Any creature hit by a basilisk\r\nmust make a saving throw vs. turn to stone or\r\nbe petrified; all equipment he carries will also be\r\nturned to stone.', 10, 2, 10, 5, 52, 14, 36, 18, 6, 900, 0, 1, 100, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite, 1d10+2'),
(12, 'Baboon, Rock', 'babr', 'Rock baboons are larger versions of normal baboons\r\nand are more intelligent. They are omnivores\r\nbut prefer meat. They are not inclined to\r\neat humans, preferring small herd animals when\r\nthey can catch such beasts. They do not make\r\ntools or weapons but will pick up bones or\r\nbranches to use as clubs.\r\nRock baboons form packs of up to 30 members,\r\neach pack led by a dominant male. They\r\nare ferocious and have vicious tempers. They do\r\nnot speak a true language, but use simple\r\nscreams to communicate warnings and needs.\r\nRock baboons will not go out of their way', 8, 2, 8, 5, 14, 4, 9, 6, 2, 20, 0, 1, 15, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'club,1d6'),
(13, 'Bat Normal', 'batn', 'Bats are nocturnal flying insectivores. They often\r\nlive in caves or abandoned buildings and\r\nfind their way about by echolocation (a type of\r\nradar using hearing and echoes to locate objects).\r\nSince they have very weak eyes, spells that affect\r\nsight (such as light) do not work on bats. However,\r\na silence 15'' radius spell will effectively\r\n"blind" a bat. Normal Animal.', 3, 2, 8, 4, 3, 4, 4, 4, 1, 5, 0, 1, 4, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite,1d2'),
(14, 'Bat Giant', 'batg', 'Bats are nocturnal flying insectivores. They often\r\nlive in caves or abandoned buildings and\r\nfind their way about by echolocation (a type of\r\nradar using hearing and echoes to locate objects).\r\nSince they have very weak eyes, spells that affect\r\nsight (such as light) do not work on bats. However,\r\na silence 15'' radius spell will effectively\r\n"blind" a bat. Normal Animal like bat normal but  bigger.', 4, 2, 9, 4, 7, 7, 6, 6, 2, 20, 0, 1, 6, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite,1d4'),
(15, 'Black bear', 'blackbea', 'Black bears have black fur and\r\nstand about 6'' tall. They are omnivores but prefer\r\nroots and berries. A black bear will not usually\r\nattack unless it is cornered and cannot\r\nescape. Adult black bears will fight to the death\r\nto protect their young. They have been known to\r\nraid camps, seeking food. They are especially\r\nfond of such treats as fresh fish and sweets.', 11, 2, 8, 4, 26, 8, 14, 6, 4, 80, 0, 1, 40, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'claw,1d3/claw,1d3/bite,1d6'),
(16, 'Grizzly', 'grizzly', 'Grizzly bears have silver-tipped\r\nbrown or reddish brown fur and stand about 9''\r\ntall. They are fond of meat and are much more\r\nlikely to attack than black bears. Grizzlies are\r\nfound in most climates, but are most common in\r\nmountains and forests.', 11, 2, 8, 4, 33, 11, 16, 8, 5, 175, 0, 1, 80, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'claw,1d4/claw,1d4/bite,1d8'),
(17, 'Polar bear', 'polarbe', 'Polar bears have white fur and\r\nstand about 11'' tall. They live in cold regions.\r\nThey usually eat fish, but often attack adventurers.\r\nThese huge bears are good swimmers, and\r\ntheir wide feet allow them to run across snow\r\nwithout sinking.', 11, 2, 8, 4, 39, 15, 17, 10, 6, 280, 0, 1, 130, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'claw,1d6/claw,1d6/bite,1d10'),
(18, 'Cave bear', 'cavebea', 'These enormous bears stand about\r\n15'' tall. They do not see well at all but hunt very\r\nwell by scent. If hungry, they will follow a track\r\nof blood until they have eaten. They prefer a diet\r\nof fresh-killed red meat and live in caves,\r\nmostly in prehistoric environments or very distant\r\nmountain areas where human civilization\r\nhas not penetrated.', 11, 2, 8, 4, 47, 17, 21, 12, 7, 450, 0, 1, 160, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'claw,1d8/claw,1d8/bite,1d10+1'),
(19, 'Bee, Giant', 'beegi', 'Giant bees, also called "killer bees," are footlong\r\ngiant bees with nasty tempers. Giant bees\r\nalways attack anyone within 30'' of their hive. If a\r\ngiant bee attack hits, the bee dies, but the creature\r\nstung must make a saving throw vs. poison\r\nor die. The stinger will work its way into the victim,\r\ninflicting 1 point of damage per round, unless\r\na character spends a round pulling it out.\r\nOwing to the great weight of their hives, giant\r\nbees prefer to build their hives in small caves and\r\nunderground areas near the surface.', 3, 1, 7, 2, 3, 4, 0, 1, 1, 5, 0, 1, 1, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'sting,1d2'),
(20, 'Fire Beetle', 'firebeet', 'Fire beetles are 2 1/2'' - long creatures\r\noften found below ground. A fire beetle\r\nhas two glowing glands above its eyes and one\r\nnear the back of its abdomen. These glands give\r\noff light in a 10'' radius and will continue to glow\r\nfor 1d6 days after they are removed.', 2, 1, 4, 1, 5, 1, 4, 1, 1, 15, 0, 1, 1, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite,2d4'),
(21, 'Oil Beetle', 'oilbee', 'Oil beetles are 3''-long giant beetles\r\nthat sometimes burrow underground. When attacked,\r\nan oil beetle squirts an oily fluid at one\r\nattacker (an attack roll is needed; the range is 5'').\r\nThe oil raises painful blisters, causing a - 2 penalty\r\non the victim''s attack rolls until cured by a cure\r\nlight wounds spell or until 24 hours have passed.', 2, 1, 4, 1, 9, 2, 7, 2, 2, 25, 0, 1, 20, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite1d6+1d4'),
(22, 'Tiger Beetle', 'tigerbee', 'Tiger beetles are 4''-long giant\r\nbeetles with a striped carapace that looks like a\r\ntiger''s skin. They are carnivores and usually prey\r\non robber flies.', 2, 1, 4, 1, 15, 4, 10, 4, 3, 50, 0, 1, 30, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite,2d6+1'),
(23, 'Beholder', 'Beholder', 'A beholder, also called an "eye tyrant" or\r\n"sphere of many eyes," looks like a large floating\r\nball (about 4'' in diameter) covered with tough\r\narmor-plated skin. Atop the beholder are ten\r\nsmall eyes on stalks, each with its own magical\r\npower. A large central eye is on the front of the\r\nbody, with a toothy mouth below it.\r\nA beholder moves by means of a slow flight\r\nthat cannot be dispelled. It speaks most languages\r\nand is extremely intelligent, cruel, and\r\ngreedy. It is normally found alone but is rarely\r\n(5% chance) found with 1d6 young (each with\r\n1/10 normal Hit Dice and range of eye effects,\r\nbite damage 1d4 points).\r\nThe beholder''s front eye always projects an\r\nanti-magic ray, which temporarily "turns off all\r\nmagic within 60'' in front of it (see "Anti-Magic"\r\nin Chapter 13). Magical weapons used within\r\nthe ray are treated as if nonmagical. Spells cast\r\nwithin it area of effect are instantly ruined; spells\r\ncast from further away are ruined when the effects\r\nget within range. The beholder will usually\r\nturn to face any character who starts casting, ruining\r\nthe spell.', 10, 16, 11, 10, 78, 77, 59, 50, 11, 4800, 0, 1, 750, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, 'bite,2d10+spell'),
(24, 'Berserker', 'Berserker', 'Berserkers are fighters who go mad in battle.\r\nMost belong to barbarian culturesÃ¢ÂÂtypically,\r\nnorthern seagoing cultures.\r\nBerserker reactions are determined normally\r\noutside of combat, but once a battle starts they\r\nwill always fight to the deathÃ¢ÂÂsometimes attacking\r\ntheir comrades in their blind rage. When\r\nfighting humans or humanlike creatures (such as\r\nkobolds, goblins or orcs), they add + 2 to their\r\nattack rolls due to their ferocity. They never retreat,\r\nsurrender, or take prisoners.', 18, 6, 10, 7, 14, 4, 7, 2, 1, 20, 0, 1, 10, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'weapon,1d8+3'),
(25, 'black Pudding', 'blackpu', 'A black pudding is a nonintelligent black\r\nblob 5 to 30 feet in diameter. Puddings are always\r\nhungry; they will attack any creature they\r\ncome across.\r\nWith their corrosive touch, they inflict 3d8\r\npoints of damage to living things, and can dissolve\r\nwood and corrode metal in one turn. They\r\ncannot affect stone.\r\nThey can travel on', 10, 1, 8, 3, 56, 8, 40, 10, 10, 1550, 0, 1, 210, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'special,3d8'),
(26, 'Blast Spore', 'blastsp', 'A blast spore looks almost exactly like a beholder\r\n(see Beholder, above). However, it is a\r\ntype of floating fungus.\r\nWhen seen in dim light, a blast spore is usually\r\nmistaken for a beholder; a character must\r\nroll 10% or less on 1d100 to tell the difference.\r\nWhen characters come within 10'', their chance\r\nfor detection improves to 25%.\r\nIf a blast spore is damaged in any way, it explodes\r\nfor 6-36 (6d6) points of damage to all\r\nwithin 20''; each victim may make a saving throw\r\nvs. wands to take half damage. This explosion\r\ndoes not shower victims with spores the way the\r\nnormal attack does.', 5, 0, 5, 3, 3, 0, 4, 2, 1, 11, 0, 1, 5, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'special,1d3'),
(27, 'Blink Dog', 'blikkd', 'This unusual creature is a small, brown-furred,\r\nrugged-looking canine with big jaws. It is not,\r\nhowever, a normal animal. It is intelligent, often\r\ntravels in packs, and uses a limited teleportation\r\nability. It can "blink out" of one spot and immediately\r\nappear ("blink in") at another. It has instincts\r\nthat prevent it from appearing in a solid\r\nobject.', 8, 9, 9, 6, 29, 22, 24, 12, 4, 125, 0, 1, 20, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite,1d6'),
(28, 'Boar normal', 'boarn', 'Wild boars generally prefer forested areas but\r\ncan be found nearly everywhere. They are omnivores\r\nand have extremely bad tempers when disturbed.\r\nThey sometimes lie in thickets in the\r\nforest and charge passersby. They do have the\r\ncharge attack special ability; if they can charge\r\nfor 20 yards before reaching their prey, they inflict\r\ndouble damage when they hit.', 9, 2, 7, 3, 16, 2, 12, 4, 3, 75, 0, 1, 28, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'tusk,2d4'),
(29, 'Boar great', 'boarg', 'Wild boars generally prefer forested areas but\r\ncan be found nearly everywhere. They are omnivores\r\nand have extremely bad tempers when disturbed.\r\nThey sometimes lie in thickets in the\r\nforest and charge passersby. They do have the\r\ncharge attack special ability; if they can charge\r\nfor 20 yards before reaching their prey, they inflict\r\ndouble damage when they hit.\r\nGreat Boars: These rare boars are huge and\r\nterrifying. They are most often found in "lost\r\nworld" settings and are occasionally used as\r\nmounts by barbaric tribes.', 9, 2, 7, 3, 52, 12, 21, 10, 10, 1555, 0, 1, 155, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'tusk,2d8'),
(30, 'Bugbear', 'Bugbear', 'Bugbears are giant hairy goblinsÃ¢ÂÂhumanoids\r\nthat grow to about 8'' tall and are covered with\r\nbristly dark fur.\r\nDespite their size and awkward walk, they\r\nmove very quietly and attack without warning\r\nwhenever they can. They surprise on a roll of 1-3\r\n(on 1d6) due to their stealth. When using weapons,\r\nthey add + 1 to all attack and damage rolls\r\nbecause of their strength', 13, 7, 7, 3, 21, 3, 10, 4, 3, 55, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'weapon,1d8+2'),
(31, 'Caecilia', 'Caecilia', 'This giant gray wormlike creature is about 30''\r\nlong. They are meat-eaters and can be found\r\nnearly anywhere.\r\nCaecilia often lie in wait in loose soil just below\r\nthe surface. Whenever a small party of animals\r\nor humans pass, they shoot up out of the\r\nground and begin biting with their large mouths\r\nand sharp teeth. An unadjusted attack roll of 19\r\nor 20 means that the caecilia has swallowed its\r\nprey whole. A victim takes 1d8 points of damage\r\neach round until the victim or the caecilia is\r\ndead.', 10, 0, 4, 3, 33, 3, 12, 4, 6, 500, 0, 1, 85, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite,2d4'),
(32, 'Camel', 'Camel', 'The camel is an ill-tempered beast, apt to bite\r\nor kick any creature that gets in its wayâ\r\nincluding its owner. It often kicks with one leg.\r\nCamels are used as pack and riding animals in\r\ndeserts and barren lands (with movement as if in\r\nclear terrain). A well-watered camel may travel\r\nfor two weeks without drinking. Camels are herbivores,\r\npreferring grasses and grains, but will\r\neat animal skin and bones when very hungry.\r\nA camel with one hump is called a dromedary,\r\nand one with two humps is a Bactrian camel.', 9, 2, 8, 2, 10, 5, 10, 3, 2, 28, 0, 1, 10, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, 'bite,1d2/hoof1d3'),
(33, 'Carrion Crawler', 'Carrioncr', 'This scavenger is a 9''-long, 3''-high manylegged\r\nworm. It can move equally well on a\r\nfloor, wall, or ceiling. Its small mouth is surrounded\r\nby eight tentacles, each 2'' long, which\r\ncan paralyze on a successful hit unless a saving\r\nthrow vs. paralysis is made. A tentacle hit does\r\nno actual damage.\r\nCarrion crawlers are known as scavengers, eating\r\nthe remains of slain animals. But they are also\r\nwilling to go after fresh meat. They will attack\r\nsmall parties of travelers, paralyzing their prey,\r\nand will eat paralyzed victims in three turns unless\r\nexcept when the carrion crawlers are being\r\nattacked.', 6, 0, 7, 2, 14, 2, 8, 3, 3, 80, 0, 1, 10, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'tentacles,1d6'),
(34, 'Cat great, mountain lion', 'catgrmo', 'This scavenger is a 9''-long, 3''-high manylegged\r\nworm. It can move equally well on a\r\nfloor, wall, or ceiling. Its small mouth is surrounded\r\nby eight tentacles, each 2'' long, which\r\ncan paralyze on a successful hit unless a saving\r\nthrow vs. paralysis is made. A tentacle hit does\r\nno actual damage.\r\nCarrion crawlers are known as scavengers, eating\r\nthe remains of slain animals. But they are also\r\nwilling to go after fresh meat. They will attack\r\nsmall parties of travelers, paralyzing their prey,\r\nand will eat paralyzed victims in three turns unless\r\nexcept when the carrion crawlers are being\r\nattacked.', 9, 2, 9, 2, 18, 4, 10, 3, 3, 80, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'claw,1d3/claw,1d3/bite,1d6'),
(35, 'Panther', 'Panther', 'Panthers are found on plains, forests,\r\nand open shrub lands. They are extremely\r\nquick and can outrun most prey over short distances.\r\nPanthers are usually black-furred.', 10, 2, 9, 2, 24, 7, 11, 4, 4, 105, 0, 1, 30, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'claw,1d4/claw,1d4/bite,1d8'),
(36, 'Lion', 'Lion', 'Lions generally live in warm climates\r\nand thrive in savannah and brush lands near deserts.\r\nThey usually hunt in groups, known as\r\nprides. Male lions have the distinctive lionmane;\r\nfemale lions do not.', 9, 2, 9, 2, 34, 14, 10, 6, 6, 180, 0, 1, 45, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'claw,1d4+2/claw,1d4+2/bite,1d8+2'),
(38, 'Sabre-tooth Tiger', 'sabreT', 'Sabre-tooth tigers are the\r\nlargest and most ferocious of the great cats. They\r\nhave oversized fangs, from which they get their\r\nname. Sabre-tooth tigers are mostly extinct, except\r\nin "lost world" areas.', 10, 2, 10, 2, 48, 20, 12, 7, 9, 600, 0, 1, 80, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'claw,1d8+1/claw,1d8+1/bite,2d8'),
(39, 'Centaur', 'Centaur', 'A centaur is a creature with the head, arms,\r\nand upper body of a man joined to the body and\r\nlegs of a horse. They are of average human intelligence\r\nand often carry weapons (clubs, lances,\r\nand bows; one weapon per creature). A centaur\r\nmay use a charge attack with a lance.\r\nCentaurs will form into small tribes or families.\r\nTheir homes are in dense thickets or woods.\r\nThe females and young will usually stay in the\r\nlair. If attacked, females and young will attempt\r\nto flee; if escape is impossible, they will fight to\r\nthe death. The young fight as 2-HD monsters,\r\nand do less damage (1d2/ld2/ld4).', 11, 10, 10, 9, 23, 14, 16, 10, 4, 85, 0, 1, 20, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, 'hoove,1d6/hoove,1d6/weapon,1d6'),
(40, 'Centipede', 'Centipede', 'A giant centipede is a foot-long insect with\r\nmany legs. Centipedes prefer dark, damp places\r\nand are often found in dungeons or on the boles\r\nand branches of trees in deep forest. They do not\r\ncommonly attack travelers, but will usually attack\r\nsomeone who disturbs them.\r\nThey attack by biting. The bite does no damage\r\nto characters, but the victim must make a\r\nsaving throw vs. poison or become violently ill\r\nfor 10 days. Characters who do not make their\r\nsaving throws move at half speed and will not be\r\nable to perform any other physical action. The\r\nbite is more effective against very small creatures,\r\nsuch as the birds and insects they eat; such\r\ncreatures must save vs. poison or die.', 4, 1, 4, 2, 3, 0, 4, 1, 1, 5, 0, 1, 0, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d2'),
(41, 'Chimera', 'Chimera', 'A chimera is a horrid combination of three\r\ndifferent creatures. It has three heads (goat, lion,\r\nand dragon), the forebody of a lion, the\r\nhindquarters of a goat, and the wings and tail of\r\na dragon.\r\nChimerae are rare, solitary creatures that are\r\nvery territorial. They usually live in wild hills but\r\nmay occasionally be found in some dungeons.\r\nThey might also live in small groupsÃÂ¢ÃÂÃÂoften\r\nmated pairs with one or two young.\r\nIn combat, the goat''s head butts, the lion''s\r\nhead bites, and the dragon''s head can bite or\r\nbreathe fire (a cone 50'' long and 10'' wide at the\r\nend, for 3d6 points of damage). The breath can\r\nonly be used three times per day. In a fight, the\r\nchimera has a 50% chance each round to use its\r\nbreath attack; once it has used all three such attacks,\r\nit will use only its other attacks', 10, 6, 11, 4, 58, 17, 37, 8, 9, 2200, 0, 1, 170, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 6, 'claw,1d3/claw,1d3/head,2d4/head,1d10/head,3d4/breath,3d6'),
(42, 'Cockatrice', 'Cockatrice', 'This is a magical monster with the head,\r\nwings, and legs of a rooster and the tail of a\r\nsnake. Its beak attack causes 1d6 points of damage.\r\nAny creature bitten or touched by a cockatrice\r\nmust make a saving throw or be turned to stone.\r\nCockatrices may be found anywhere.', 10, 2, 9, 4, 33, 6, 21, 4, 5, 475, 0, 1, 50, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'break,1d8+1'),
(43, 'Crocodile normal', 'Crocodileno', 'Crocodiles are commonly found in tropical and semitropical swamps and rivers. Sometimes they are seen in underground rivers and seas.\r\nAwkward on land, crocodiles do not stray far\r\nfrom water and will spend hours floating just under\r\nthe surface. At such times, they can be mistaken\r\nfor logs.', 10, 2, 10, 3, 11, 1, 10, 2, 2, 25, 0, 1, 5, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite, 1d6'),
(44, 'Crocodile large', 'Crocodilelar', 'Like Crocodile normal, but bigger', 10, 2, 10, 3, 30, 2, 15, 3, 5, 225, 0, 1, 15, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite, 2d6'),
(45, 'Crocodile giant', 'Crocodilegia', 'Like Crocodile large, but bigger', 10, 2, 10, 3, 110, 4, 45, 4, 15, 1850, 0, 1, 65, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite, 3d6+3'),
(46, 'crab giant', 'crab', 'Giant crabs are nonintelligent animals found\r\nin shallow waters, coastal rivers, and buried in\r\nsand on beaches. They cannot swim. The common\r\ngiant crab is 8'' in diameter, but larger specimens\r\nmay be found (up to 6 Hit Dice, Damage\r\n3d6 points per claw).\r\nThey are always hungry and will attack and eat\r\nanything that moves. Salt-water giant crabs have\r\na slightly different appearance than fresh-water\r\ngiant crabs.', 9, 2, 9, 2, 20, 1, 10, 1, 3, 200, 0, 1, 10, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, 'pincers 1d4+1/ pincers,1d4+1'),
(47, 'Cyclops', 'Cyclops', 'Giant crabs are nonintelligent animals found\r\nin shallow waters, coastal rivers, and buried in\r\nsand on beaches. They cannot swim. The common\r\ngiant crab is 8'' in diameter, but larger specimens\r\nmay be found (up to 6 Hit Dice, Damage\r\n3d6 points per claw).\r\nThey are always hungry and will attack and eat\r\nanything that moves. Salt-water giant crabs have\r\na slightly different appearance than fresh-water\r\ngiant crabs.', 13, 9, 9, 4, 92, 8, 55, 8, 13, 2150, 0, 1, 110, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'club, 3d12+3'),
(48, 'Dinosaur, Aquatic large', 'dinoalarg', 'Some large land herbivores\r\nhave marine counterparts, similar in appearance\r\nexcept for smaller legs, and fins instead of claws.\r\nSome look like snakes with unarmored turtlelike\r\nbodies. Only the largest aquatic dinosaurs have\r\nhigh morale. Carnivorous types will be more aggressive\r\nand territorial. A very large specimen\r\n(20 + HD) may be able to swallow man-sized\r\nopponents on an attack roll of 20; treasure may\r\nbe found inside its body.', 10, 3, 10, 2, 135, 11, 66, 11, 20, 3250, 0, 1, 350, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, 'bite, 4d8/ flipper, 2d6'),
(49, 'Dinosaur, Aquatic small', 'dinoasmall', 'Only primitive fish and eels fall\r\ninto this category. Most flee if disturbed by anything\r\n1 foot long or more.', 9, 3, 10, 2, 40, 3, 33, 5, 6, 425, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite 2d4'),
(50, 'Dinosaur, Aquatic armored', 'dinoaromr', 'All the dinosaurs in this category\r\nare slow in comparison to other marine\r\nlife, because of their large shells. They are the\r\nancestors of modern turtles.', 9, 3, 10, 2, 21, 1, 15, 2, 3, 80, 0, 1, 12, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'bite 1d4');
