-- phpMyAdmin SQL Dump
-- version 2.11.9.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generato il: 09 Apr, 2009 at 02:15 AM
-- Versione MySQL: 5.0.67
-- Versione PHP: 5.2.4

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `mikesac_mikesac`
--

--
-- Dump dei dati per la tabella `NPC`
--

INSERT INTO `NPC` (`id`, `name`, `image`, `description`, `base_str`, `base_int`, `base_dex`, `base_cha`, `base_pl`, `base_pm`, `base_pa`, `base_pc`, `level`, `px`, `status`, `area`, `gold`, `xml_dialog`, `xml_items`, `xml_behave`, `ismonster`, `nattack`, `attack`) VALUES
(1, 'Goblin', 'goblin', 'Goblins are small humanoid monsters. They vary in height from about 3 to 3 ½ feet (91 - 106 cm) and weigh 40 to 45 pounds (21 - 24 kg). They walk upright even though their arms nearly reach their knees. Their eyes vary from red to yellow and are usually dull and glazed. They have a broad nose that sits on a flat face with pointed ears and a wide mouth. Their mouth contains small, but sharp fangs. Their skin pigment ranges from a deep red through nearly any shade of orange to yellow. Members of the same tribe tend to have the same skin color. Based on their ability scores and the encumbrance rules the average goblin would be able to lift about 60 pounds over his head.', 5, 5, 5, 5, 12, 6, 10, 5, 1, 10, 0, 1, 1, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'Unarmed,1d1'),
(2, 'Hobgoblin', 'hobgoblin', 'Hobgoblins exist in perpetual war against all other races, believing that "lesser" species are fit only for battle fodder. In mixed groups, hobgoblin officers often lead units of goblins or orcs, whom they bully and make to feel inferior. Other peoples find them paranoid, insulting, and dismissive, while hobgoblins in turn treat all others as potential threats. Hobgoblin mercenaries may offer their services to powerful and wealthy members of other races, however.', 5, 5, 5, 5, 12, 6, 10, 5, 1, 10, 0, 1, 1, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, 'Unarmed,1d1'),
(3, 'Actaeon', 'Actaeon', 'This solitary creature is a protector of woodland\r\ncreatures. The actaeon is 9'' tall, with the\r\narms, torso, and facial features of a human but\r\nthe antlers and lower legs of an elk; its whole\r\nbody is covered with brown elklike hide.Actaeons are members of the woodland community\r\nalong with centaurs, dryads, etc. They\r\nare sufficiently bold and rare that they are renowned\r\nheroes of these forest folk. Actaeon\r\nsometimes work with druids to preserve the\r\nsafety of the woods, especially if a dangerous\r\nthreat is involved.', 16, 12, 12, 7, 108, 56, 66, 45, 11, 2200, 0, 1, 500, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, 'ld6 + 6/ld6 + 6'),
(4, 'Adaptor', 'Adaptor', 'Adaptors are a peculiar race native to all\r\nplanes of existence. They are very intelligent,\r\nand their ancient race has greater and wider\r\nknowledge than any sage, but their cultural philosophy\r\ndemands that they not pass their great\r\nknowledge between planes and human cultures.\r\nInstead, they travel and observe civilization\r\nthroughout the planes, exchanging information\r\nonly among themselves.', 12, 14, 10, 9, 79, 72, 46, 48, 8, 1100, 0, 1, 125, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, '1d8 + 4 /1d8 + 4'),
(5, 'Aerial Servant', 'Aerialser', 'Aerial servants are humanoid in shape. They\r\nappear to be man-shaped figures of roiling fog;\r\nthey are eerie and menacing.\r\nAerial servants are beings native to the elemental\r\nplane of Air. On their home plane, they\r\nare known by a name which sounds like\r\n"haoou.', 10, 12, 13, 9, 128, 96, 143, 96, 16, 3890, 0, 1, 800, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '4d8'),
(6, 'Sheep', 'Sheep', 'This common animal are often in herd.', 6, 6, 6, 5, 16, 10, 10, 10, 2, 25, 0, 2, 15, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d6'),
(7, 'Ant, Giant', 'antg', 'Giant ants are black ants about 6'' long. They are\r\nomnivores and will attack anything edible that lies\r\nin their path (no reaction roll); if they win, they carry\r\ntheir kills back to the nest. Once engaged in\r\ncombat, they will fight to the death, even trying to\r\ncross flames to reach their opponents.\r\nA giant ant nest looks like a large, bare hill.\r\nGiant ant nests are not as heavily populated as\r\nthose of smaller ants.', 3, 3, 9, 4, 27, 10, 22, 14, 4, 125, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '2d6'),
(8, 'Ape, Snow', 'apeg', 'Snow apes are squat, baboonlike creatures\r\nwith shaggy white fur. They are somewhat intelligent,\r\nand often make simple tools like clubs or\r\nsharpened bones. They cannot, however, grasp\r\nmore complicated concepts, such as the use of a\r\nbow and arrow.', 3, 4, 9, 4, 22, 13, 11, 9, 4, 75, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d8+1'),
(9, 'Ape, White', 'apew', 'White apes have lost their color due to many\r\nyears of living in caves. They are nocturnal herbivores,\r\nlooking for fruits and vegetables at\r\nnight.\r\nThey do not go out of their way to attack characters;\r\nif approached by humans and demihumans\r\nand given a chance to flee, they will do\r\nso. But if creatures approach their lair, the apes\r\nwill threaten the intruders. If their threats are ignored,\r\nthey will attack', 3, 2, 8, 3, 22, 10, 15, 9, 4, 75, 0, 1, 25, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, '1d4/ld4'),
(10, 'Bandit', 'Bandit', 'It''s like a human thief how lives in town or in the wood.', 10, 11, 10, 10, 11, 6, 6, 6, 1, 10, 0, 1, 10, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d6'),
(11, 'Basilisk', 'Basilisk', 'A basilisk is a 10''-long lizard; it looks much\r\nlike a large snake with four legs and a crownlike\r\ngrowth on its head. It may be of any color, but is\r\nusually very bright and distinctive. It is sometimes\r\ncalled the "king of snakes."\r\nThe basilisk is a nonintelligent but very magical\r\nlizard. It lives in underground caverns or wild\r\nand tangled thickets. Any creature hit by a basilisk\r\nmust make a saving throw vs. turn to stone or\r\nbe petrified; all equipment he carries will also be\r\nturned to stone.', 10, 2, 10, 5, 52, 14, 36, 18, 6, 900, 0, 1, 100, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d10+2'),
(12, 'Baboon, Rock', 'babr', 'Rock baboons are larger versions of normal baboons\r\nand are more intelligent. They are omnivores\r\nbut prefer meat. They are not inclined to\r\neat humans, preferring small herd animals when\r\nthey can catch such beasts. They do not make\r\ntools or weapons but will pick up bones or\r\nbranches to use as clubs.\r\nRock baboons form packs of up to 30 members,\r\neach pack led by a dominant male. They\r\nare ferocious and have vicious tempers. They do\r\nnot speak a true language, but use simple\r\nscreams to communicate warnings and needs.\r\nRock baboons will not go out of their way', 8, 2, 8, 5, 14, 4, 9, 6, 2, 20, 0, 1, 15, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d6'),
(13, 'Bat Normal', 'batn', 'Bats are nocturnal flying insectivores. They often\r\nlive in caves or abandoned buildings and\r\nfind their way about by echolocation (a type of\r\nradar using hearing and echoes to locate objects).\r\nSince they have very weak eyes, spells that affect\r\nsight (such as light) do not work on bats. However,\r\na silence 15'' radius spell will effectively\r\n"blind" a bat. Normal Animal.', 3, 2, 8, 4, 3, 4, 4, 4, 1, 5, 0, 1, 4, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d2'),
(14, 'Bat Giant', 'batg', 'Bats are nocturnal flying insectivores. They often\r\nlive in caves or abandoned buildings and\r\nfind their way about by echolocation (a type of\r\nradar using hearing and echoes to locate objects).\r\nSince they have very weak eyes, spells that affect\r\nsight (such as light) do not work on bats. However,\r\na silence 15'' radius spell will effectively\r\n"blind" a bat. Normal Animal like bat normal but  bigger.', 4, 2, 9, 4, 7, 7, 6, 6, 2, 20, 0, 1, 6, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d4'),
(15, 'Black bear', 'blackbea', 'Black bears have black fur and\r\nstand about 6'' tall. They are omnivores but prefer\r\nroots and berries. A black bear will not usually\r\nattack unless it is cornered and cannot\r\nescape. Adult black bears will fight to the death\r\nto protect their young. They have been known to\r\nraid camps, seeking food. They are especially\r\nfond of such treats as fresh fish and sweets.', 11, 2, 8, 4, 26, 8, 14, 6, 4, 80, 0, 1, 40, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, '1d3/1d3/1d6'),
(16, 'Grizzly', 'grizzly', 'Grizzly bears have silver-tipped\r\nbrown or reddish brown fur and stand about 9''\r\ntall. They are fond of meat and are much more\r\nlikely to attack than black bears. Grizzlies are\r\nfound in most climates, but are most common in\r\nmountains and forests.', 11, 2, 8, 4, 33, 11, 16, 8, 5, 175, 0, 1, 80, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, '1d4/1d4/1d8'),
(17, 'Polar bear', 'polarbe', 'Polar bears have white fur and\r\nstand about 11'' tall. They live in cold regions.\r\nThey usually eat fish, but often attack adventurers.\r\nThese huge bears are good swimmers, and\r\ntheir wide feet allow them to run across snow\r\nwithout sinking.', 11, 2, 8, 4, 39, 15, 17, 10, 6, 280, 0, 1, 130, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, '1d6/1d6/1d10'),
(18, 'Cave bear', 'cavebea', 'These enormous bears stand about\r\n15'' tall. They do not see well at all but hunt very\r\nwell by scent. If hungry, they will follow a track\r\nof blood until they have eaten. They prefer a diet\r\nof fresh-killed red meat and live in caves,\r\nmostly in prehistoric environments or very distant\r\nmountain areas where human civilization\r\nhas not penetrated.', 11, 2, 8, 4, 47, 17, 21, 12, 7, 450, 0, 1, 160, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 3, '1d8/1d8/1d10+1'),
(19, 'Bee, Giant', 'beegi', 'Giant bees, also called "killer bees," are footlong\r\ngiant bees with nasty tempers. Giant bees\r\nalways attack anyone within 30'' of their hive. If a\r\ngiant bee attack hits, the bee dies, but the creature\r\nstung must make a saving throw vs. poison\r\nor die. The stinger will work its way into the victim,\r\ninflicting 1 point of damage per round, unless\r\na character spends a round pulling it out.\r\nOwing to the great weight of their hives, giant\r\nbees prefer to build their hives in small caves and\r\nunderground areas near the surface.', 3, 1, 7, 2, 3, 4, 0, 1, 1, 5, 0, 1, 1, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d2'),
(20, 'Fire Beetle', 'firebeet', 'Fire beetles are 2 1/2'' - long creatures\r\noften found below ground. A fire beetle\r\nhas two glowing glands above its eyes and one\r\nnear the back of its abdomen. These glands give\r\noff light in a 10'' radius and will continue to glow\r\nfor 1d6 days after they are removed.', 2, 1, 4, 1, 5, 1, 4, 1, 1, 15, 0, 1, 1, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '2d4'),
(21, 'Oil Beetle', 'oilbee', 'Oil beetles are 3''-long giant beetles\r\nthat sometimes burrow underground. When attacked,\r\nan oil beetle squirts an oily fluid at one\r\nattacker (an attack roll is needed; the range is 5'').\r\nThe oil raises painful blisters, causing a - 2 penalty\r\non the victim''s attack rolls until cured by a cure\r\nlight wounds spell or until 24 hours have passed.', 2, 1, 4, 1, 9, 2, 7, 2, 2, 25, 0, 1, 20, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d6+1d4'),
(22, 'Tiger Beetle', 'tigerbee', 'Tiger beetles are 4''-long giant\r\nbeetles with a striped carapace that looks like a\r\ntiger''s skin. They are carnivores and usually prey\r\non robber flies.', 2, 1, 4, 1, 15, 4, 10, 4, 3, 50, 0, 1, 30, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '2d6+1'),
(23, 'Beholder', 'Beholder', 'A beholder, also called an "eye tyrant" or\r\n"sphere of many eyes," looks like a large floating\r\nball (about 4'' in diameter) covered with tough\r\narmor-plated skin. Atop the beholder are ten\r\nsmall eyes on stalks, each with its own magical\r\npower. A large central eye is on the front of the\r\nbody, with a toothy mouth below it.\r\nA beholder moves by means of a slow flight\r\nthat cannot be dispelled. It speaks most languages\r\nand is extremely intelligent, cruel, and\r\ngreedy. It is normally found alone but is rarely\r\n(5% chance) found with 1d6 young (each with\r\n1/10 normal Hit Dice and range of eye effects,\r\nbite damage 1d4 points).\r\nThe beholder''s front eye always projects an\r\nanti-magic ray, which temporarily "turns off all\r\nmagic within 60'' in front of it (see "Anti-Magic"\r\nin Chapter 13). Magical weapons used within\r\nthe ray are treated as if nonmagical. Spells cast\r\nwithin it area of effect are instantly ruined; spells\r\ncast from further away are ruined when the effects\r\nget within range. The beholder will usually\r\nturn to face any character who starts casting, ruining\r\nthe spell.', 10, 16, 11, 10, 78, 77, 59, 50, 11, 4800, 0, 1, 1350, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 2, '2d10+spell'),
(24, 'Berserker', 'Berserker', 'Berserkers are fighters who go mad in battle.\r\nMost belong to barbarian cultures typically,\r\nnorthern seagoing cultures.\r\nBerserker reactions are determined normally\r\noutside of combat, but once a battle starts they\r\nwill always fight to the deathâsometimes attacking\r\ntheir comrades in their blind rage. When\r\nfighting humans or humanlike creatures (such as\r\nkobolds, goblins or orcs), they add + 2 to their\r\nattack rolls due to their ferocity. They never retreat,\r\nsurrender, or take prisoners.', 18, 6, 10, 7, 14, 4, 7, 2, 1, 20, 0, 1, 10, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d8+3'),
(25, 'black Pudding', 'blackpu', 'A black pudding is a nonintelligent black\r\nblob 5 to 30 feet in diameter. Puddings are always\r\nhungry; they will attack any creature they\r\ncome across.\r\nWith their corrosive touch, they inflict 3d8\r\npoints of damage to living things, and can dissolve\r\nwood and corrode metal in one turn. They\r\ncannot affect stone.\r\nThey can travel on', 10, 1, 8, 3, 56, 8, 40, 10, 10, 1550, 0, 1, 10, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '3d8'),
(26, 'Blast Spore', 'blastsp', 'A blast spore looks almost exactly like a beholder\r\n(see Beholder, above). However, it is a\r\ntype of floating fungus.\r\nWhen seen in dim light, a blast spore is usually\r\nmistaken for a beholder; a character must\r\nroll 10% or less on 1d100 to tell the difference.\r\nWhen characters come within 10'', their chance\r\nfor detection improves to 25%.\r\nIf a blast spore is damaged in any way, it explodes\r\nfor 6-36 (6d6) points of damage to all\r\nwithin 20''; each victim may make a saving throw\r\nvs. wands to take half damage. This explosion\r\ndoes not shower victims with spores the way the\r\nnormal attack does.', 5, 0, 5, 3, 3, 0, 4, 2, 1, 11, 0, 1, 5, 'basedialog.xml', 'baseitem.xml', 'baseact.xml', 1, 1, '1d3');
